[package]
name = "network-flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphviz-rust-bla = "0.*"
dot-structures = "0.1.0"
dot-generator = "0.2.0"